console.group("My Code Group!");
console.time("CodeID!");
console.log("Hello, From JavaScript!");
console.log("Harsh Kale!");
console.log(4+3);
console.log(7);
console.log(true);
console.log([1,2,3,4,5,6,7]);
console.log({name: "Harsh Kale", age: 18, isTopper: true, marks: [100, 100, 100, 100]});
console.table({name: "Harsh Kale", age: 18, isTopper: true, marks: [100, 100, 100, 100]});
console.warn("This is a warning!");
// console.clear(); 
console.timeEnd("CodeID!");
console.assert(1 > 2/* 2 > 1 */, "This is not possible!");
console.error("This is an ERROR!");
console.groupEnd();
console.debug({name: "Harsh Kale", age: 18, isTopper: true, marks: [100, 100, 100, 100]});